### ISSUE TITLE
Missing api_key on the Verify API (2FA)

### ISSUE THREAD

**Issue by romeoonisim** [Vonage/vonage-laravel#16] opened 2023-03-20 17:56 UTC
Hey there, I'm struggling with the new Vonage package (v1.0.3) to make it work on Laravel 9 with PHP 8.0.2. I'm using it only for 2FA, so without the notification package. 

I managed to make it to start the verification by providing the key and secret inside the start function
```
Vonage::verify()->start([
    'number' => $user->phone,
    'brand'  => config('app.name'),
    'key' => config('services.vonage.key'),
    'secret' => config('services.vonage.secret'),
]);
```

But, for the actual `check` function it seems that the package is not adding the key and secret inside the body of the request, but rather on the Header as a Token. (Check \Vonage\Client\Credentials\Handler\BasicHandler). Here is my code:
```
Vonage::verify()->check(
   $request->session()->get('verify:request_id'),
   $request->code
);
```

I get the following error message: `Missing api_key`. From what I checked the package is trying to send a POST request to https://developer.vonage.com/en/api/verify#verifyCheck but this endpoint needs the api_key and api_secret as body parameters rather than a Header Token. I saw this to confirm: https://developer.vonage.com/en/getting-started/concepts/authentication

Worth mentioning is that I've already registered Vonage as a Facade in config/app.php and published the config/vonage.php. ENV Variables are also set:
```
VONAGE_KEY="xxxxxxx"
VONAGE_SECRET="xxxxxxx"
VONAGE_APP_NAME="XXXX"
VONAGE_APP_VERSION="1.0.3"
```

Please let me know if you encountered this issue or is something that I'm doing wrong. Thank you!

**Comment by romeoonisim** [comment] 2023-03-21 09:42
Ended up doing something like this for the check process instead of relying on the check function from Verify/Client:
```
Vonage::verify()->getApiResource()->create([
    'request_id' => $request->session()->get('verify:request_id'),
    'code'  => $request->code,
    'api_key' => VONAGE_KEY from env,
    'api_secret' => VONAGE_SECRET from env,
], '/check/json');
```

But the issue still remains open, I think the root cause might be from `vonage-php-sk-core` where I've also opened a ticket: https://github.com/Vonage/vonage-php-sdk-core/issues/391

**Comment by SecondeJK** [comment] 2023-03-21 10:24
Looks like I might have configured the Verify Auth handling incorrectly - I'll close this one as the problem is upstream and fix it at source

**Closed by SecondeJK** 2023-03-21 10:24 UTC
